# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test:
    working_directory: ~/clubhub-emails
    docker:
      # specify the version you desire here
      - image: circleci/node:10.16.0

    steps:
      - checkout
      
      # Download and cache dependencies
      - restore_cache:
          key: v1.001-dependencies-{{ checksum "package.json" }}
  
      - run: make node_modules

      - save_cache:
          paths:
            - node_modules
          key: v1.001-dependencies-{{ checksum "package.json" }}

      # run tests!

      - run:
          name: Build
          command: make

      - run:
          name: Build
          command: make test
          
workflows:
  version: 2
  test:
    jobs: 
      - test
